# Generated by Django 3.2.4 on 2021-06-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatureC', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pressure', models.PositiveSmallIntegerField()),
                ('humidity', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
